### ISSUE TITLE
error building using bazel 

### ISSUE THREAD

**Issue by abhishekbalu** [PINTO0309/TensorflowLite-flexdelegate#3]
sudo bazel build \
--config=monolithic \
--config=noaws \
--config=nohdfs \
--config=noignite \
--config=nokafka \
--config=nonccl \
--config=v2 \
--define=tflite_convert_with_select_tf_ops=true \
--define=with_select_tf_ops=true \
//tensorflow/lite:libtensorflowlite.so

not working for tensorflow 2.3.0, python 3.6, bazel:3.6.1

**Comment by PINTO0309** [comment]
Tensorflow v2.3.0 + Bazel 3.1.0
```bash
$ sudo bazel build \
--config=monolithic \
--config=noaws \
--config=nohdfs \
--config=nonccl \
--config=v2 \
--define=tflite_pip_with_flex=true \
--define=tflite_with_xnnpack=true \
//tensorflow/tools/pip_package:build_pip_package
```

**Comment by unparalleled-ysj** [comment]
@PINTO0309 Hello, can you provide me with the compiled so, I have always had problems with the compilation

**Comment by PINTO0309** [comment]
@unparalleled-ysj 
You can use the installer with FlexDelegate and XNNPACK enabled. If you need to install it by means other than the installer below, please at least share the error message. I do not know what is happening to you.
**https://github.com/PINTO0309/TensorflowLite-bin.git**
