### ISSUE TITLE
Flex Ops

### ISSUE THREAD

**Issue by StuartIanNaylor** [PINTO0309/TensorflowLite-flexdelegate#4]
Hey pinto just wondering if you will have another look at flex ops.

https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md#crnn

Google research have done a great repo for all state of art KWS for tensorflow lite and have been trying to work out how to get the above working with TFL as a CRNN I thought was naturally a steaming NN and slightly confused at the non-stream version as presume they are applying 1 sec images to a naturally stream model just for comparison and also what is crnn_state as why? But that is another question but there are a whole load of models that would be really cool to get going on a Pi.

Its also really interesting with the upcoming 2.5 as if I am reading right we should be able to use quantisation and flex ops and we could expect 2-3x perf with little accuracy loss over the full framework.

I was wondering if you could give it a try as so far my attempts have been a fail but much work has been added to flex ops with the biggest of quantisation in 2,5.

Is it of any interest as hoping so? 

Also the models of https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md#crnn have focused on best accuracy for comparison I was wondering if you had done anything with https://www.tensorflow.org/model_optimization ?

**Comment by PINTO0309** [comment]
Thank you for the suggestion. My working policy is clear. I will generate a Flex-enabled installer the day after the official release is announced. For example, the following repository is the repository where the pip package with FlexDelegate enabled is committed. I plan to build it the day after the v2.5.0 branch is created and moved to release. It is released every three months, so I expect v2.5.0 to be released soon.
**https://github.com/PINTO0309/TensorflowLite-bin**

**Comment by StuartIanNaylor** [comment]
Thats great as been trying to work out the release schedule as the FlexDelegate I think will be a big one for choice of models in 2.5 as really interested in what the perf gains will be for TFL with FlexOps.
I have been aware of your great TFL Pi community wheels for a while but the natural streaming models often used such as GRU, CRNN or SVDF until FlexOps has excluded my interest.
MFCC is also in the Core now but the CRNN is a true hybrid of CNN then GRU and wondered if not CRNN then maybe you are also curious to add more audio based models to your model zoo?

I will be eagerly checking for releases many thanks.

**Comment by etyhh** [comment]
Hey pinto, would you update this repository since flexdelegate in tensorflow 2.5 has much improved

**Comment by PINTO0309** [comment]
@etyhh 
https://github.com/PINTO0309/TensorflowLite-bin
